# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mASQNEDDu66T4PD3uTlKxs9sp7wMQQUI
"""

!curl -s https://course.fast.ai/setup/colab | bash

from fastai import *
from fastai.vision import *
import numpy as np
from fastai.metrics import accuracy

from google.colab import drive
drive.mount('/content/drive/')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

data.show_batch(rows=3, figsize=(10,10))

my_trained_mod = cnn_learner(data, models.resnet34, metrics=[accuracy])
my_trained_mod.fit_one_cycle(6)

my_trained_mod.lr_find()
my_trained_mod.recorder.plot()

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation1')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC2'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation2')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC3'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation3')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC4'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation4')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC5'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation5')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC6'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation6')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC7'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation7')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC8'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation8')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC9'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation9')

tfms = get_transforms(do_flip=False)
path = '/content/drive/My Drive/fastAI/IC10'
data = ImageDataBunch.from_folder(path,ds_tfms=tfms, size=240)

my_trained_mod.load('ImageClassifier_CrossValidation1')

my_trained_mod.fit_one_cycle(8, max_lr=slice(1e-4,1e-3))

my_trained_mod.save('ImageClassifier_CrossValidation10')